src/app/app-routing.module.ts
src/app/app.component.html
src/app/find-help/find-help-routing.module.ts
src/app/find-help/find-help.component.spec.ts
src/app/find-help/find-help.component.ts
src/app/find-help/find-help.module.ts
src/app/give-help/give-help-routing.module.ts
src/app/give-help/give-help.component.spec.ts
src/app/give-help/give-help.component.ts
src/app/give-help/give-help.module.ts
src/app/welcome/welcome-routing.module.ts
src/app/welcome/welcome.component.spec.ts
src/app/welcome/welcome.component.ts
src/app/welcome/welcome.module.ts

This pull request is for main routes
/
/szukaj-pomocy
/daj-pomoc
It is also prepared for
/szukaj-pomocy/nocleg

POM-71 Welcome screen routing initialized

---

src/app/welcome/category-navigation/category-navigation.component.scss
src/app/welcome/hero/hero.component.scss
src/assets/styles/buttons.scss

This pull request resolves all errors and warnings in the app.

Fix ESLint and Prettier errors

---

karma.conf.js
package-lock.json
src/app/app.component.spec.ts
src/app/app.component.ts
src/index.html

I'm not sure about the changes in `package-lock.json`.
We might consider renaming the repo (it has that typo too)

Fix 'pomogam' typo

---

src/app/shared/components/type-of-help/type-of-help.component.html
src/app/shared/components/type-of-help/type-of-help.component.scss
src/app/welcome/hero/hero.component.html
src/app/welcome/hero/hero.component.scss
src/assets/styles/buttons.scss
src/assets/styles/utilities.scss
src/assets/styles/variables.scss
src/styles.scss
src/translations/pl_PL.ts

Added wave at the bottom of hero component, RWD styles and some utility classes
Changes in `type-of-help.component` are for accessibiltity and fix focus frame

pom-11: homepage rwd design, utitlity classes

---

src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/app/find-help/accommodation-search/accommodation-search-form/accommodation-search-form.component.html
src/app/find-help/accommodation-search/accommodation-search.module.ts
src/app/welcome/category-navigation/category-navigation.component.html
src/app/welcome/hero/hero.component.scss
src/app/welcome/welcome.component.html
src/assets/styles/buttons.scss
src/assets/styles/variables.scss
src/styles.scss
src/translations/pl_PL.ts

Add a light grey background and header styling dependent on the route
Add styling for the search button
Add padding to main content
Add translations bindings

Homepage and category view design fixes

---

src/app/find-help/find-help.component.scss

find-help max-width to fit exactly all categories

---

src/app/app.component.spec.ts
src/app/cities-search/cities-search.component.spec.ts
src/app/core/components/more-info-link/more-info-link.component.spec.ts
src/app/find-help/accommodation-search/accommodation-search-form/accommodation-search-form.component.spec.ts
src/app/find-help/accommodation-search/accommodation-search.component.spec.ts
src/app/find-help/find-help.component.spec.ts
src/app/find-help/material-aid-search/material-aid-search-form/material-aid-search-form.component.spec.ts
src/app/find-help/material-aid-search/material-aid-search.component.spec.ts
src/app/find-help/transport-search/transport-search-form/transport-search-form.component.spec.ts
src/app/find-help/transport-search/transport-search.component.spec.ts
src/app/give-help/accommodation-form/accommodation-form.component.spec.ts
src/app/give-help/give-help.component.spec.ts
src/app/shared/components/type-of-help/type-of-help.component.spec.ts
src/app/welcome/welcome.component.spec.ts

Fix all component tests

---

generate-api.sh
mock/data/accommodation.ts
mock/data/city.ts
mock/data/index.ts
mock/index.ts
mock/operations/accommodation.ts
mock/operations/city.ts
mock/operations/index.ts
mock/tsconfig-mock.json
package-lock.json
package.json
src/proxy.conf.json

POM-162 - mock-server

---

src/app/core/translations/pl_PL.ts
src/app/give-help/transport-form/transport-form.component.html
src/app/give-help/transport-form/transport-form.module.ts
src/app/shared/components/datepicker/datepicker.component.html
src/app/shared/components/datepicker/datepicker.component.ts
src/app/shared/components/datepicker/datepicker.module.ts
src/app/shared/components/field-error/errors.ts

- add validators to form
- datepicker add required flag

POM-198 Transport Form Validation

---

src/app/give-help/accommodation-form/accommodation-form.component.html
src/app/give-help/accommodation-form/accommodation-form.module.ts

POM-195 Accommodation Form Validation

---

src/app/app.component.ts
src/app/core/site-header/site-header.component.html
src/app/core/site-header/site-header.component.scss
src/app/core/site-header/site-header.component.ts

Change language switcher so the button displays active language instead of placeholder text

Language switcher

---

src/app/core/site-header/site-header.component.html
src/app/core/site-header/site-header.component.ts

Fix [POM-266](https://jira.sysopspolska.pl/browse/POM-226)

Fix mobile menu state on navbar item click

---

package-lock.json
package.json
src/app/shared/components/datepicker/datepicker.component.html
src/app/shared/components/datepicker/datepicker.component.ts
src/app/shared/components/datepicker/datepicker.module.ts

Add i18n for datepicker component

POM-204 [f] wyszukiwarka kalendarz - tłumaczenie nazw miesięcy/dni tygodnia

---

src/app/statement/statement.component.html
src/app/statement/statement.component.scss
src/app/statement/statement.component.ts
src/app/welcome/dashboard/dashboard.component.html
src/assets/styles/_vars.scss
src/assets/styles/utilities.scss
src/assets/styles/variables.scss

https://user-images.githubusercontent.com/18722471/159121800-3af56823-f584-4c6c-952a-d6e0c36458a8.mov

feat: Statement page design

---

src/app/core/api/api/myOffersResource.service.ts

Fix headerow do http zapytania

POM-257 brak listy ogloszen dodanych przez zalogowanego uzytkownika

---

src/app/core/api/api/myOffersResource.service.ts
src/app/core/api/model/accommodationOffer.ts
src/app/core/api/model/accommodationOfferDefinitionDTO.ts
src/app/core/api/model/materialAidOffer.ts
src/app/core/api/model/materialAidOfferDefinitionDTO.ts
src/app/core/api/model/transportOffer.ts
src/app/core/api/model/transportOfferDefinitionDTO.ts
src/app/find-help/view-offer-accommodation/view-offer-accommodation.component.ts
src/app/find-help/view-offer-material-aid/view-offer-material-aid.component.ts
src/app/find-help/view-offer-transport/view-offer-transport.component.ts
src/app/give-help/accommodation-form/accommodation-form.component.ts
src/app/give-help/material-aid-form/material-aid-form.component.ts
src/app/give-help/transport-form/transport-form.component.ts

Also, remove UI workarounds for latest API fixes that are no longer needed

Regenerate API

---

mock/data/accommodation.ts
mock/data/material-aid.ts
mock/data/transport.ts
mock/data/user.ts

Without this, it's impossible to run the proxy, even the one linking to the
real server.

Add missing phoneNumber to mock responses

---

src/app/find-help/search-result/search-result-attribute/search-result-attribute.component.html
src/app/find-help/search-result/search-result.component.html
src/app/find-help/search-result/search-result.component.scss

POM-285 [UC.05] #stylowanie Ikony wyświetlane z za małym kontrastem (za małe opacity)

---

src/app/find-help/reply-offer/reply-offer.component.html
src/assets/styles/overrides.scss

Pom 280 consents

---

src/app/give-help/accommodation-form/accommodation-form.component.html
src/app/give-help/material-aid-form/material-aid-form.component.html

I made a mistake when resolving merge conflicts in #135 before merging, leading
to type issues. This fixes them.
Ref #135

Fix bad git merge

---

.github/workflows/lint.yaml

For now this only runs the linter and prettier, no tests yet because `ng test` fails to build for me locally.
I'll be trying to get it working so that we can start running some automated tests.

Add a basic workflow for Github Actions

---

src/app/give-help/accommodation-form/accommodation-form.component.ts
src/app/give-help/material-aid-form/material-aid-form.component.ts
src/app/give-help/transport-form/transport-form.component.ts
src/app/shared/components/cities-search/cities-search.component.ts
src/app/shared/consts.ts
src/proxy.conf.json

poprawka do replace dla pola location

Pom 246 235 location valid

---

src/app/app.module.ts
src/app/core/api-helper/api-helper.module.ts
src/app/core/api-helper/index.ts
src/app/core/core.module.ts
src/app/core/interceptor/field-mapper.ts
src/app/core/interceptor/http-error.interceptor.ts
src/app/core/interceptor/interceptor.module.ts
src/app/core/interceptor/language.interceptor.ts
src/app/core/translations/pl_PL.ts
src/app/give-help/accommodation-form/accommodation-form.component.ts
src/app/give-help/material-aid-form/material-aid-form.component.ts
src/app/give-help/transport-form/transport-form.component.ts
src/app/shared/components/breadcrumbs/breadcrumb/breadcrumb.component.ts
src/app/shared/index.ts

Niektóre pola nie są typowane, niestety nie dostaniemy tego w intefrejsach z API.
Uporządkowany app.module.ts, przeniesione moduły do core.module.ts

POM-201 - obsługa błędów, dodanie headera

---

src/app/core/site-footer/site-footer/site-footer.component.html
src/app/core/site-footer/site-footer/site-footer.component.scss

- change visibility logos
- change layout footer nav

POM-328 Site footer

---

src/app/shared/components/snackbar/snackbar.component.html

[pom-389](https://jira.sysopspolska.pl/browse/POM-389) ikona snackbara w złym miejscu

POM-389 ikona snackbara w zlym miejscu

---

src/app/core/translations/pl_PL.ts

https://jira.sysopspolska.pl/browse/POM-386

POM-386 naprawa literówki

---

src/app/find-help/accommodation-search/accommodation-search-form/accommodation-search-form.component.html
src/app/find-help/material-aid-search/material-aid-search-form/material-aid-search-form.component.html
src/app/find-help/transport-search/transport-search-form/transport-search-form.component.html
src/app/shared/components/cities-search/cities-search.component.ts

```Obecnie po wpisaniu hasła spoza słownika wyświetla się wiadomość walidacyjna, ale wciąż możliwe jest wyszukanie. Oczekiwany rezultat - zablokowany przycisk "Wyszukaj", jeśli pokazujemy błąd walidacji pola.```
Preview:

POM 305 Disabling search for unselected city

---

mock/data/transport.ts
mock/data/user.ts
src/app/find-help/search-result/search-result.component.ts
src/app/find-help/view-offer-accommodation/view-offer-accommodation.component.html
src/app/find-help/view-offer-accommodation/view-offer-accommodation.component.ts
src/app/find-help/view-offer-material-aid/view-offer-material-aid.component.html
src/app/find-help/view-offer-material-aid/view-offer-material-aid.component.ts
src/app/find-help/view-offer-transport/view-offer-transport.component.html
src/app/find-help/view-offer-transport/view-offer-transport.component.ts
src/app/my-account/my-account/my-account.component.ts
src/app/shared/components/back-to-list/back-to-list.component.ts

POM-342 wróć do listy - obsługa oryginalnych query params (przeniesienie z https://github.com/coi-gov-pl/gui-web-pomogamukrainie-forum/pull/196/files)

---

src/app/core/site-header/site-header.component.ts

Fix Ukrainian and Russian lang labels

---

src/app/find-help/accommodation-search/accommodation-search-form/accommodation-search-form.component.html
src/app/find-help/accommodation-search/accommodation-search.module.ts
src/app/find-help/transport-search/transport-search-form/transport-search-form.component.html
src/app/find-help/transport-search/transport-search.module.ts
src/app/give-help/accommodation-form/accommodation-form.component.html
src/app/give-help/transport-form/transport-form.component.html
src/app/shared/validators/min-max-validate.directive.ts

- add error field on search form
- change MinMax direcitve

POM-267 Number validation

---

src/app/find-help/reply-offer/reply-offer.component.html
src/app/find-help/reply-offer/reply-offer.component.scss

Remove cursor pointer as it's not clickable.

POM-408 #stage [UC.06] Ukryty link w nagłówku odpowiedzi

---

src/app/find-help/search-result/search-result.component.html
src/app/find-help/transport-search/transport-search.component.html

Taki format jest OK w języku ukraińskim: https://en.wikipedia.org/wiki/Date_and_time_notation_in_Ukraine

Ujednolicenie formatu daty, zamiast Mar 24, 2022 jest 14/03/2022 (wcześniej "Mar" nie był tłumaczony)

---

src/app/find-help/search-result/search-result-attribute/search-result-attribute.component.html
src/app/find-help/search-result/search-result-attribute/search-result-attribute.component.scss
src/app/find-help/search-result/search-result.component.html
src/app/find-help/search-result/search-result.component.scss
src/app/find-help/view-offer-accommodation/view-offer-accommodation.component.html
src/app/find-help/view-offer-material-aid/view-offer-material-aid.component.html
src/app/find-help/view-offer-transport/view-offer-transport.component.html

Also, switch our custom `first-case-up` class to Bootstrap's `text-capitalize`.

POM-249 Capitalize cities in remaining places

---

src/app/find-help/accommodation-search/accommodation-search.component.html
src/app/find-help/accommodation-search/accommodation-search.component.scss
src/app/find-help/accommodation-search/accommodation-search.module.ts
src/app/find-help/find-help.component.html
src/app/find-help/find-help.module.ts
src/app/find-help/material-aid-search/material-aid-search.component.html
src/app/find-help/material-aid-search/material-aid-search.module.ts
src/app/find-help/transport-search/transport-search.component.html
src/app/find-help/transport-search/transport-search.module.ts
src/app/find-help/view-offer-accommodation/view-offer-accommodation.component.html
src/app/find-help/view-offer-accommodation/view-offer-accommodation.module.ts
src/app/find-help/view-offer-material-aid/view-offer-material-aid.component.html
src/app/find-help/view-offer-material-aid/view-offer-material-aid.module.ts
src/app/find-help/view-offer-transport/view-offer-transport.component.html
src/app/find-help/view-offer-transport/view-offer-transport.module.ts

POM-420 View offer is now without categories
